Navigation login 1
wolox-training/am-android pull request #3
Opened 2022-07-20 16:32 UTC by AleMathus

### **Summary**
Navigation implemented and added to the Home Page and Sign Up screen, added intent to the Wolox page for terms and conditions.

### **Trello**

[(Link a la card de Trello)
](https://trello.com/c/YChBs3eJ)

### **Screenshot**

https://user-images.githubusercontent.com/108141974/180035032-ca70b5e5-891c-4920-8bf7-35be353c6d08.mov

2022-07-20 17:24 UTC, jcruz-wolox requested changes
I only have one comment, the rest is well for me.

2022-07-20 17:24 UTC, jcruz-wolox commented on app/src/main/java/com/example/myapplication/ui/LoginFragment.kt
> +                    Intent(Intent.ACTION_VIEW, Uri.parse("https://www.wolox.com.ar/"))
You could put this url inside a private static constant (companion object).

2022-07-21 13:37 UTC, LisandroDiMeo approved these changes
Agree with Jona's comment 👍

2022-07-21 13:44 UTC, ffasitella requested changes
There's a single issue to fix before merging. Good job!

2022-07-21 13:44 UTC, ffasitella commented on app/src/main/java/com/example/myapplication/ui/LoginFragment.kt
> +            }
There's no need to call the viewmodel here. You can just make the redirection like:
```
signUpButton.setOnClickListener {
    goToSignUp()
}
```
As a general rule, don't call the viewmodel unless you are making a request or something like that.

2022-07-21 13:44 UTC, ffasitella commented on app/src/main/java/com/example/myapplication/vm/LoginViewModel.kt
> +        get() = _validEmail
You are storing a boolean for both valid email and invalid email. You can create a LiveData called validEmail, and set it true or false.

2022-07-21 14:14 UTC, ffasitella approved these changes
🚀

2022-07-22 12:20 UTC, jcruz-wolox approved these changes

2022-07-22 12:28 UTC, merged